# EVN

In [1]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

# 행렬연산

## 데이터

In [2]:
hidden = np.random.randint(-9, 10, (5, 4)) / 10
hidden

array([[ 0.5, -0.1,  0.8, -0.7],
       [ 0.5,  0.2,  0.4, -0.8],
       [ 0.7, -0.4, -0.9,  0.8],
       [-0.9, -0.2, -0.5,  0.4],
       [ 0.8, -0.5, -0.8,  0.7]])

## element wise sum

In [ ]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden + arg

In [ ]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden + arg

In [ ]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden + arg

In [ ]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden + arg

In [ ]:
hidden + 1

In [ ]:
1 + hidden

## element wise multiplication

In [ ]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden * arg

In [ ]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden * arg

In [ ]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden * arg

In [12]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden * arg

(array([[-0.1]]), array([[-0.05,  0.01, -0.08,  0.07],
        [-0.05, -0.02, -0.04,  0.08],
        [-0.07,  0.04,  0.09, -0.08],
        [ 0.09,  0.02,  0.05, -0.04],
        [-0.08,  0.05,  0.08, -0.07]]))

In [13]:
hidden * 2

array([[ 1. , -0.2,  1.6, -1.4],
       [ 1. ,  0.4,  0.8, -1.6],
       [ 1.4, -0.8, -1.8,  1.6],
       [-1.8, -0.4, -1. ,  0.8],
       [ 1.6, -1. , -1.6,  1.4]])

In [14]:
2 * hidden

array([[ 1. , -0.2,  1.6, -1.4],
       [ 1. ,  0.4,  0.8, -1.6],
       [ 1.4, -0.8, -1.8,  1.6],
       [-1.8, -0.4, -1. ,  0.8],
       [ 1.6, -1. , -1.6,  1.4]])

## matrix multiplication

In [16]:
hidden

array([[ 0.5, -0.1,  0.8, -0.7],
       [ 0.5,  0.2,  0.4, -0.8],
       [ 0.7, -0.4, -0.9,  0.8],
       [-0.9, -0.2, -0.5,  0.4],
       [ 0.8, -0.5, -0.8,  0.7]])

In [15]:
arg = np.random.randint(-9, 10, (4, 5)) / 10
arg, np.matmul(hidden, arg)

(array([[ 0.7, -0.2,  0.1,  0.7,  0.4],
        [ 0.4,  0.3, -0.7,  0.2,  0.1],
        [ 0.7,  0.8,  0.1, -0.8, -0.9],
        [-0.6, -0.1,  0.5,  0.4, -0.7]]),
 array([[ 1.29,  0.58, -0.15, -0.59, -0.04],
        [ 1.19,  0.36, -0.45, -0.25,  0.42],
        [-0.78, -1.06,  0.66,  1.45,  0.49],
        [-1.3 , -0.32,  0.2 , -0.11, -0.21],
        [-0.62, -1.02,  0.7 ,  1.38,  0.5 ]]))

In [17]:
val = np.zeros((hidden.shape[0], arg.shape[1]))
val

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
for row in range(hidden.shape[0]):
    row_v = hidden[row]
    for col in range(arg.shape[1]):
        col_v = arg[:, col]
        val[row][col] = np.dot(row_v, col_v)
val

array([[ 1.29,  0.58, -0.15, -0.59, -0.04],
       [ 1.19,  0.36, -0.45, -0.25,  0.42],
       [-0.78, -1.06,  0.66,  1.45,  0.49],
       [-1.3 , -0.32,  0.2 , -0.11, -0.21],
       [-0.62, -1.02,  0.7 ,  1.38,  0.5 ]])